import Head from 'next/head';
import MaintainMode from '../components/MaintainMode';

const Home = () => (
  <div>
    <Head>
      <title>Create Next App</title>
      <meta name="description" content="Generated by create next app" />
      <link rel="icon" href="/favicon.ico" />
    </Head>

    <main>
      <MaintainMode />
    </main>

  </div>
);

export default Home;
