import Head from 'next/head';
import ImgCraousel from "../components/ImgCraousel";

const Home = () => (
    <div>
        <Head>
            <title>Create Next App</title>
            <meta name="description" content="Generated by create next app"/>
            <link rel="icon" href="/favicon.ico"/>
        </Head>

        <main>
            <div className="w-full h-52 md:h-[500px]">
                <img src="/asset/slider_img/slider_1.jpg" className='w-full h-full' alt=""/>
            </div>

            <div className="container mx-auto my-16 text-center">
                <h1 className='text-2xl md:text-4xl mb-5 px-3'>
                    <span className='font-bold'>FIND THE BEST</span> Car For You
                </h1>
                <p className='px-5 md:px-24'>
                    There are many variations of passages of Lorem Ipsum available, but the majority have suffered
                    alteration in some form, by injected humour, or randomised words which don't look even slightly
                    believable. If you are going to use a passage of Lorem Ipsum, you need to be sure there isn't
                    anything embarrassing hidden in the middle of text.
                </p>
                <div className="my-8">
                    <ImgCraousel />
                </div>
            </div>
        </main>

    </div>
);

export default Home;
